// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type LtiPlatform struct {
	ID                   uuid.UUID
	Issuer               string
	ClientID             string
	DeploymentID         pgtype.Text
	AuthEndpoint         pgtype.Text
	TokenEndpoint        pgtype.Text
	JwksUri              pgtype.Text
	RegistrationEndpoint pgtype.Text
	CreatedAt            pgtype.Timestamptz
}
