// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: platform.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createPlatform = `-- name: CreatePlatform :one
INSERT INTO lti_platforms (issuer,
                           client_id,
                           deployment_id,
                           auth_endpoint,
                           token_endpoint,
                           jwks_uri,
                           registration_endpoint)
VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING id, issuer, client_id, deployment_id, auth_endpoint, token_endpoint, jwks_uri, registration_endpoint, created_at
`

type CreatePlatformParams struct {
	Issuer               string
	ClientID             string
	DeploymentID         pgtype.Text
	AuthEndpoint         pgtype.Text
	TokenEndpoint        pgtype.Text
	JwksUri              pgtype.Text
	RegistrationEndpoint pgtype.Text
}

func (q *Queries) CreatePlatform(ctx context.Context, arg CreatePlatformParams) (LtiPlatform, error) {
	row := q.db.QueryRow(ctx, createPlatform,
		arg.Issuer,
		arg.ClientID,
		arg.DeploymentID,
		arg.AuthEndpoint,
		arg.TokenEndpoint,
		arg.JwksUri,
		arg.RegistrationEndpoint,
	)
	var i LtiPlatform
	err := row.Scan(
		&i.ID,
		&i.Issuer,
		&i.ClientID,
		&i.DeploymentID,
		&i.AuthEndpoint,
		&i.TokenEndpoint,
		&i.JwksUri,
		&i.RegistrationEndpoint,
		&i.CreatedAt,
	)
	return i, err
}

const deletePlatform = `-- name: DeletePlatform :exec
DELETE
FROM lti_platforms
WHERE id = $1
`

func (q *Queries) DeletePlatform(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePlatform, id)
	return err
}

const getPlatformByID = `-- name: GetPlatformByID :one
SELECT id, issuer, client_id, deployment_id, auth_endpoint, token_endpoint, jwks_uri, registration_endpoint, created_at
FROM lti_platforms
WHERE id = $1
`

func (q *Queries) GetPlatformByID(ctx context.Context, id uuid.UUID) (LtiPlatform, error) {
	row := q.db.QueryRow(ctx, getPlatformByID, id)
	var i LtiPlatform
	err := row.Scan(
		&i.ID,
		&i.Issuer,
		&i.ClientID,
		&i.DeploymentID,
		&i.AuthEndpoint,
		&i.TokenEndpoint,
		&i.JwksUri,
		&i.RegistrationEndpoint,
		&i.CreatedAt,
	)
	return i, err
}

const getPlatformByIssuerAndClientID = `-- name: GetPlatformByIssuerAndClientID :one
SELECT id, issuer, client_id, deployment_id, auth_endpoint, token_endpoint, jwks_uri, registration_endpoint, created_at
FROM lti_platforms
WHERE issuer = $1
  AND client_id = $2
`

type GetPlatformByIssuerAndClientIDParams struct {
	Issuer   string
	ClientID string
}

func (q *Queries) GetPlatformByIssuerAndClientID(ctx context.Context, arg GetPlatformByIssuerAndClientIDParams) (LtiPlatform, error) {
	row := q.db.QueryRow(ctx, getPlatformByIssuerAndClientID, arg.Issuer, arg.ClientID)
	var i LtiPlatform
	err := row.Scan(
		&i.ID,
		&i.Issuer,
		&i.ClientID,
		&i.DeploymentID,
		&i.AuthEndpoint,
		&i.TokenEndpoint,
		&i.JwksUri,
		&i.RegistrationEndpoint,
		&i.CreatedAt,
	)
	return i, err
}

const listPlatforms = `-- name: ListPlatforms :many
SELECT id, issuer, client_id, deployment_id, auth_endpoint, token_endpoint, jwks_uri, registration_endpoint, created_at
FROM lti_platforms
ORDER BY created_at DESC
`

func (q *Queries) ListPlatforms(ctx context.Context) ([]LtiPlatform, error) {
	rows, err := q.db.Query(ctx, listPlatforms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LtiPlatform
	for rows.Next() {
		var i LtiPlatform
		if err := rows.Scan(
			&i.ID,
			&i.Issuer,
			&i.ClientID,
			&i.DeploymentID,
			&i.AuthEndpoint,
			&i.TokenEndpoint,
			&i.JwksUri,
			&i.RegistrationEndpoint,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateClientID = `-- name: UpdateClientID :exec
UPDATE lti_platforms
SET client_id = $2
WHERE issuer = $1
`

type UpdateClientIDParams struct {
	Issuer   string
	ClientID string
}

func (q *Queries) UpdateClientID(ctx context.Context, arg UpdateClientIDParams) error {
	_, err := q.db.Exec(ctx, updateClientID, arg.Issuer, arg.ClientID)
	return err
}
